name: Run Python Tests

on:
  push:
    branches: [ main ]  # Draait bij elke push naar de main branch
  pull_request:
    branches: [ main ]  # Draait ook bij pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Draai de tests op een Linux-omgeving

    steps:
    - uses: actions/checkout@v3  # Haalt je repo op

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Gebruik Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest
